name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "37 17 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["8.1", "8.2", "8.3", "8.4"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: |
          docker build php/8 --build-arg PHP_VERSION=${{ matrix.version }} -t beninho/php:${{ matrix.version }}
          docker save -o ${{ matrix.version }}.tar beninho/php:${{ matrix.version }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-${{ matrix.version }}
          path: ${{ matrix.version }}.tar
  
  push:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        version: ["8.1", "8.2", "8.3", "8.4"]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: php-${{ matrix.version }}
      
      - name: Load Docker image
        run: docker load -i ${{ matrix.version }}.tar
      
      - name: Show Docker images
        run: docker images
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Push Docker image
        run: docker push beninho/php:${{ matrix.version }}
      
      - name: Push latest tag (if applicable)
        if: matrix.version == '8.4'
        run: |
          docker tag beninho/php:8.4 beninho/php:latest
          docker push beninho/php:latest

  build-apache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build Apache Docker image
        run: |
          docker build httpd/2.4 -t beninho/httpd:2.4
          docker save -o httpd_2.4.tar beninho/httpd:2.4
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: httpd-2.4
          path: httpd_2.4.tar

  push-apache:
    runs-on: ubuntu-latest
    needs: build-apache
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: httpd-2.4
      
      - name: Load Docker image
        run: docker load -i httpd_2.4.tar
      
      - name: Show Docker images
        run: docker images
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Push Apache Docker image
        run: |
          docker push beninho/httpd:2.4
          docker tag beninho/httpd:2.4 beninho/apache:2.4
          docker push beninho/apache:2.4
